In [1]:
!pip install numpy

In [34]:
import numpy as np

In [35]:
a=[1,2,3,1,4,5]
print(type(a))
b=np.array(a)
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [36]:
c=np.array([1,2,4])
d=np.array([2,7,9])
print(c-d)
print(c+d)
print(c*d)
print(c/d)
print(c//d)

[-1 -5 -5]
[ 3  9 13]
[ 2 14 36]
[0.5        0.28571429 0.44444444]
[0 0 0]


In [37]:
c=np.array([1,2,4])
d=np.array([2,7,9])
print(d-c)
print(d+c)
print(d*c)
print(d/c)
print(d//c)

[1 5 5]
[ 3  9 13]
[ 2 14 36]
[2.   3.5  2.25]
[2 3 2]


In [41]:
1//2 #floor division

0

In [42]:
1/2 #int_division

0.5

In [43]:
e=np.array([[10,20,30],[40,50,60]])
print(e.ndim) 
print(e.shape)
print(e.size)
print(e.dtype)
print(e.nbytes)

2
(2, 3)
6
int64
48


In [44]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [47]:
np.eye(1)

array([[1.]])

In [48]:
f=np.array([2,4,8])
g=np.array([4,8,10])
h=np.dot(a,b)
print(h)

56


In [49]:
f=np.array([2,4,8])
g=np.array([4,8,10])
k=np.array([[10,20,30],[40,50,60]])
i=np.transpose(k)
j=np.concatenate([f,g])
l=k.flatten()
print(i)
print(j)
print(l)


[[10 40]
 [20 50]
 [30 60]]
[ 2  4  8  4  8 10]
[10 20 30 40 50 60]
